### ISSUE TITLE
getEmptyValueByFieldType returns NULL value by mistake

### ISSUE THREAD

**Issue by vstuber** [contao/core#8477] opened 2016-09-13 10:03 UTC
The function "getEmptyValueByFieldType" first checks whether the field's sql definition contains "NULL" but not "NOT NULL" and returns NULL if this is the case. If it's not, the function checks whether the field has one of the following types: 'binary', 'varbinary', 'tinyblob', 'blob', 'mediumblob', 'longblob'.

If it does, NULL is returned, even though the function never made sure that NULL is actually allowed for this field.

A field defined as "varbinary(128) NOT NULL default ''" causes the function to return NULL which results in a fatal error when this value is written to the database.

Some extensions still use field definitions like this, especially since for quite some time this was contao's definition for alias fields, which, of course, has also been used by extension developers.

Since Contao 3.5.14 (I think) this function is also used when copying records in the backend which means that copying db records with varbinary alias fields causes the system to crash.

**Comment by leofeyer** [comment] 2016-09-16 12:16
@contao/developers /cc

**Comment by ausi** [comment] 2016-09-16 13:15
I was able to reproduce it with:

```php
$GLOBALS['TL_DCA']['tl_content']['fields']['test_field'] = array(
	'eval' => array('doNotCopy' => true),
	'sql' => "varbinary(128) NOT NULL default ''",
);
```

Which results in a *“Query error: Column 'test_field' cannot be null”* when trying to duplicate a content element.

I think we should remove [Widget.php:1529-1532](https://github.com/contao/core/blob/549738f9a41974d963bd09a3a83ae0f46f887f01/system/modules/core/library/Contao/Widget.php#L1529-L1532) to fix this issue.

**Comment by vstuber** [comment] 2016-09-16 14:20
> I think we should remove Widget.php:1529-1532 to fix this issue.

This way we wouldn't get NULL as the empty value for a varbinary field (or blob etc.) even if it was a valid value.

I suggest that, instead of
```php
elseif (in_array($type, array('binary', 'varbinary', 'tinyblob', 'blob', 'mediumblob', 'longblob')))
{
	return null;
}
```

we use something like

```php
elseif (in_array($type, array('binary', 'varbinary', 'tinyblob', 'blob', 'mediumblob', 'longblob')))
{
	return strpos($sql, 'NOT NULL') === false ? null : '';
}
```

**Comment by leofeyer** [comment] 2016-09-16 14:30
Fixed in 073c1c3cea9d95e5c49ae7139fb4155469b14a45.

**Comment by fritzmg** [comment] 2016-09-16 14:33
@vstuber no I think definitions like `varbinary(128) NULL` will be catched by
```php
if (strpos($sql, 'NULL') !== false && strpos($sql, 'NOT NULL') === false)
{
	return null;
}
```
before that.

**Comment by ausi** [comment] 2016-09-21 08:01
I think we can improve this further if we change

```php
if (strpos($sql, 'NULL') !== false && strpos($sql, 'NOT NULL') === false)
```

to

```php
if (strpos($sql, 'NOT NULL') === false)
```

because `NULL` is the default.

**Comment by leofeyer** [comment] 2016-09-21 08:34
Then `null` would be returned for everything that does not contain `NOT NULL` wouldn't it?

```sql
`tstamp` int(10) default '0'
```

`strpos($sql, 'NOT NULL')` is `false`, therefore the method would return `null` instead of `0`.

**Closed by leofeyer** 2016-09-21 08:34 UTC
Labels: defect

**Comment by ausi** [comment] 2016-09-21 09:18
> In this case `strpos($sql, 'NOT NULL')` is `false`, therefore the method would return `null` instead of `0`.

Which would be right, because `null` *is* the empty value for `int(10) default '0'`. Currently `int(10) default '0'` and `int(10) NULL default '0'` will produce different values even though they represent the exact same SQL column.

**Comment by leofeyer** [comment] 2016-09-21 12:15
Then I guess the method should have been called `getDefaultValueByFieldType()`. The fact is that we are using the method to return `0` if the field definition is `int(10) NULL default '0'`.

https://github.com/contao/core/blob/master/system/modules/core/classes/Versions.php#L291

**Comment by ausi** [comment] 2016-09-21 12:23
But for `getDefaultValueByFieldType()` we should probably return the real default value, so that for `int(10) default '123'` the value `123` gets returned.

**Comment by leofeyer** [comment] 2016-09-21 12:32
Maybe. Anyway, the purpose of the existing method is to convert an empty string into the suitable empty value depending on the field type. And we are expecting it to return `0` for numeric fields.

**Comment by ausi** [comment] 2016-09-21 12:46
Then I don’t see the problem with my suggested change. All `default '0'` fields in the core do also have `NOT NULL`, so nothing changes here. But IMO `int(10) default '0'` and `int(10) NULL default '0'` should both return the same value to be consistent.

**Comment by leofeyer** [comment] 2016-09-21 13:23
True.

**Comment by leofeyer** [comment] 2016-09-21 14:44
Changed in cce5e516682367ffb58298dab196526f779a1e09.

**Comment by aschempp** [comment] 2016-09-26 06:05
FYI I'm using the same in the Doctrine integration: https://github.com/aschempp/contao-core-bundle/commit/e7fc25444bc65e2bf226ee26fb7db8ebb3856f41#diff-ecdfb51ac371b19aded651b8b47ff381R138

You might want to use `stripos` though?

**Comment by leofeyer** [comment] 2016-09-27 07:25
Changed in cff4c1a71510950f0c71271d26608f1283f7804d. I also applied `strtolower()` to `$type`.
