### ISSUE TITLE
4.4: Error Forward page. In Lightbox no radio buttons

### ISSUE THREAD

**Issue by jankout** [contao/core#8737] opened 2017-06-27 07:52 UTC
When I create a forward page with internal link and want to add the link with the lightbox no radio buttons appear. See video
![forward page ligtbox no radio buttons](https://user-images.githubusercontent.com/3715050/27576715-3f62c734-5b1e-11e7-81d7-d359ef69802f.gif)

**Comment by aschempp** [comment] 2017-06-27 07:54
Duplicate of https://github.com/contao/core-bundle/issues/883

**Closed** 2017-06-27 09:08 UTC
