### ISSUE TITLE
News: issue with internal links and multi-domain setups

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7922] opened 2015-07-14 12:09 UTC
If you use a Contao installation with a multi-domain setup and news entries with internal page or article links (under "Redirect target"), the function `ModuleNews::generateNewsUrl` does not build the URL correctly, if the target is on a different domain than the current page. 

e.g. [line #339 in ModuleNews.php](https://github.com/contao/core/blob/3.5.0/system/modules/news/modules/ModuleNews.php#L339) simply uses `Controller::generateFrontendUrl` without checking for the domain or without using the 4th parameter `$blnFixDomain` (available since Contao 3.3.0) which would check for the domain as well.

There is an old issue that already mentions this (#3765), it also indicates that the same problem might still exist in search results as well, but I haven't checked for that. Possibly the Events and FAQ modules are affected as well.

In the mean time it can be fixed for news with this extension:

* [[news_domainfix](https://contao.org/en/extension-list/view/news_domainfix.en.html)]
* [fritzmg/contao-news-domainfix](https://github.com/fritzmg/contao-news-domainfix)

**Comment by leofeyer** [comment] 2015-07-22 12:44
This is actually a duplicate of #6743.

**Comment by fritzmg** [comment] 2015-11-25 16:08
@leofeyer I just want to reiterate this here: since you posted the following here

> we are only fixing URLs when forwarding to another page in Contao 3 and 4.

Aside from the page type `PageForward` you are also able to create page forwards in news entries, by choosing __Page__ under __Redirect target__ in the properties of the news. As mentioned in this issue, this forward also does not work, if the target page is on a different domain than the news entry is displayed.

However, this issue was flagged as a duplicate of #6743 and thus might only get fixed in Contao 5, even though you want to fix page forwards in Contao 3 and 4.

**Comment by leofeyer** [comment] 2015-11-25 16:13
@fritzmg I will look into this again.

**Comment by fritzmg** [comment] 2015-11-25 16:46
Ok, thank you. I can understand if the default news url (to the news archive's reader page) is not fixed due to backwards compatibility reasons. But the page forward should be fixed imho.

**Comment by fritzmg** [comment] 2016-02-01 10:50
Any update on this for Contao 3.5.7 (since it is still closed)? The lack of proper parameters for `\Controller::generateFrontendUrl` also causes problems for RSS Feeds and possibly sitemaps.

**Comment by leofeyer** [comment] 2016-02-18 14:32
The discussion is now here: #8204

**Closed by leofeyer** 2016-02-18 14:32 UTC
