### ISSUE TITLE
Wrong headline for calendar event

### ISSUE THREAD

**Issue by romancieslik** [contao/core#8077] opened 2015-10-19 20:27 UTC
On
[main.php?do=calendar&table=tl_calendar_events&id=7&act=edit](https://localhost/contao/main.php?do=calendar&table=tl_calendar_events&id=7&act=edit)
there's a headline with the name of the parent calendar. This Name derives from the ID of the calendar entry. This is wrong. 

Exampe: When I edit event 21, the calendar's name is being obtained from calendar 21. 

![screen shot 2015-10-19 at 22 23 06](https://cloud.githubusercontent.com/assets/343699/10590272/18d2f372-76b0-11e5-829e-c0fe0f969113.png)

**Comment by Aybee** [comment] 2015-10-19 21:40
I can not force an error in the online demo. How can we force a wrong headline in the demo?

**Comment by leofeyer** [comment] 2015-10-20 08:41
@romancieslik How do I reproduce the issue with the Contao official demo? Either [online](http://demo.contao.org/contao/) or via the [extension repository](https://contao.org/en/extension-list/view/official_demo.de.html).

**Comment by romancieslik** [comment] 2015-10-20 08:42
I will do this - later or tomorrow.

**Comment by romancieslik** [comment] 2015-10-20 09:19
Can't reproduce it in the demo. The title is different there: it does not show any title.
http://demo.contao.org/contao/main.php?do=calendar&table=tl_calendar_events&id=5&act=edit
See my screenshot and compare it with my local screenshot.
![screen shot 2015-10-20 at 11 18 15](https://cloud.githubusercontent.com/assets/343699/10603059/58e4203c-771c-11e5-8394-14b317fd658c.png)


btw, I updated to 3.5.4 and the error remains.

**Comment by fritzmg** [comment] 2015-10-20 12:02
I can't reproduce this directly. However, I was able to reproduce the following behavior:
* Create a lot of different Calendars (with different names)
* Click on the edit button of any of the Calendars
* Then click on @romancieslik link to edit the event with ID 5
* The calendar's title at the top will be from a seemingly random calendar (not necessarily the calendar with ID 5).

It seems to depend on which calendar you entered before you click the link. However, the title shown will not be from the calendar you were editing before.

**Comment by Aybee** [comment] 2015-10-20 13:25
Found something out.

In the listview click on the **tool icon** "Edit the event setting".
Now you see archive title in headline - **correct**
Browser **go back**
In the listview click on the **pencil** icon "Edit event ID 6"
Now click on the **tool icon** "Edit the settings of the article" (article?)
Now you won't see the archive title in headline - **wrong**

**Comment by romancieslik** [comment] 2015-10-20 13:46
Good to see that others run into the same issue. 
In my case, it is not randomly, but every time the same wrong title.

**Comment by leofeyer** [comment] 2015-11-17 11:56
The only thing I was able to reproduce is the issue reported by @Aybee.

@fritzmg I was not able to reproduce this. Can you elaborate on your test setup please?

@romancieslik If the issue does not occur in the online demo (a.k.a. a fresh installation without any changes or third-party extensions), the error does not seem to occur in the Contao core.

**Comment by fritzmg** [comment] 2015-11-17 12:00
> @fritzmg I was not able to reproduce this. Can you elaborate on your test setup please?

This was on the official Contao Demo. Hm, there weren't any additional steps other than those I described.

**Comment by leofeyer** [comment] 2015-11-18 12:35
@fritzmg That's correct (even though a little odd), because Contao needs to store the calendar URL in the session. Now if you manually open the edit URL of an event belonging to another calendar, Contao will show the name of the calendar stored in the session in the breadcrumb menu.

However, this case can never happen if you only click your way through the back end.

**Comment by leofeyer** [comment] 2015-11-18 12:41
@Aybee This also explains your issue: If you edit the event settings from the list view, the session value (`CURRENT_ID`) will be the one from the **calendar**. However, if you edit the event settings from the parent view, the session value will be the one from the **event** and thus the title of the **calendar** cannot be shown.

**Comment by leofeyer** [comment] 2015-11-18 12:41
Since the original issue cannot be reproduced, I'm closing the ticket.

**Closed by leofeyer** 2015-11-18 12:41 UTC
Labels: invalid

**Comment by fritzmg** [comment] 2015-11-18 12:47
> @fritzmg That's correct (even though a little odd), because Contao needs to store the calendar URL in the session. Now if you manually open the edit URL of an event belonging to another calendar, Contao will show the name of the calendar stored in the session in the breadcrumb menu.
> 
> However, this case can never happen if you only click your way through the back end.

Yeah, I figured it's done only via the session.
