### ISSUE TITLE
[bug] rss feeds 2

### ISSUE THREAD

**Issue by DVeris** [contao/core#7679] opened 2015-03-10 07:45 UTC
https://github.com/contao/core/issues/7398

1) add news (unpublish)

![image](https://cloud.githubusercontent.com/assets/1255917/6458613/90758d9c-c196-11e4-9788-273792d89b61.png)

2) add news content elements and follow the link "Edit article"

![image](https://cloud.githubusercontent.com/assets/1255917/6458648/18e0fde2-c197-11e4-9e32-a892af156453.png)

3) put checkbox Publish item and push "Save and close"

you will find yourself in news content elements (the picture above)
AND RSS FEED ISN'T UPDATED

then (for example) follow the link "Home" (or Logout)
AND RSS FEED ISN'T UPDATED

**Comment by DVeris** [comment] 2015-03-16 13:13
hmm...
news without news content elements - RSS FEED ISN'T UPDATED

**Comment by DVeris** [comment] 2015-03-20 08:37
Leo, please, fix this bugs.

**Comment by leofeyer** [comment] 2015-03-20 10:56
> Leo, please, fix this bugs.

@DVeris The issue is assigned to a milestone an will be taken care of. No need to hustle!

**Comment by leofeyer** [comment] 2015-03-23 09:37
Fixed in 94488be73c4beb5e69b55c36df3beacee6ea5944.

**Comment by DVeris** [comment] 2015-03-23 10:08
thanks!

but what about it:

another problem:

i have two rss

rss1:

car (selected)
food (selected)
house (selected)

rss2:

car (selected)
food (!!!not selected!!!)
house (selected)

when add news in news archive "food" - RSS FEED ISN'T UPDATED (rss1)

**Comment by DVeris** [comment] 2015-03-24 08:30
leo, please fix another problem with rss

**Comment by DVeris** [comment] 2015-03-26 09:20
i don't know
but new news archive don't update rss xml...

Leo, please testing rss feeds

**Comment by DVeris** [comment] 2015-03-26 09:25
https://github.com/contao/core/issues/7398

**Comment by DVeris** [comment] 2015-03-26 09:26
maybe session cached?
and new news archive not seen

**Comment by leofeyer** [comment] 2015-03-26 11:01
> i have two rss
> 
> rss1:
> 
> car (selected)
> food (selected)
> house (selected)
> 
> rss2:
> 
> car (selected)
> food (!!!not selected!!!)
> house (selected)
> 
> when add news in news archive "food" - RSS FEED ISN'T UPDATED (rss1)

I was not able to reproduce this.

**Closed by leofeyer** 2015-03-26 11:01 UTC
Labels: defect

**Comment by DVeris** [comment] 2015-04-01 11:16
after update contao
old news archives works fine
new news archives - RSS FEED ISN'T UPDATED

all cache was deleted

**Comment by DVeris** [comment] 2015-04-03 05:20
Leo, please testing this:
when 1 admin and 1 user

for user - works (RSS FEED UPDATED)
for me (admin) - RSS FEED ISN'T UPDATED

i dont know how explain it
how to show it

maybe enable debug?

**Comment by DVeris** [comment] 2015-04-06 08:45
hmm...

https://github.com/contao/core/issues/7696
maybe it's related?

when i commenting error code - rss works fine
