### ISSUE TITLE
3.5.6: versioning no more working …?

### ISSUE THREAD

**Issue by pswerbung** [contao/core#8141] opened 2015-12-01 10:46 UTC
I was also in de Contao Demo and in my own installation: in Contao 3.5.6 versioning seems to add the system-log entry but there is no pulldown above the content-element or module anymore. What's wrong?

**Comment by pswerbung** [comment] 2015-12-01 10:53
… after several savings it now seems to work. So we have an issue with the first version(s). They're not correctly catched!

**Comment by aschempp** [comment] 2015-12-01 11:06
Be aware that a new version is only created if you change something on the record...

**Comment by leofeyer** [comment] 2015-12-01 11:11
How do I reproduce this in the online demo?

**Comment by pswerbung** [comment] 2015-12-01 12:09
It's possible when Login as Admin, Access Modules «Applications – Listing», Change the title, hit enter to save. No Version is made. Reedit, Enter … still no version. Then add a Headline (was empty before): version is created ;-)

**Comment by leofeyer** [comment] 2016-02-17 14:28
I have debugged the issue. It is caused by the change discussed in #7730:

https://github.com/contao/core/blob/master/system/modules/core/classes/Versions.php#L219

* If there is a record that has been created a long time ago (like in the Contao demo), the timestamp of its first version is set to the last revision date of the record.
* When the record is changed, Contao purges this first version, because it is older than the version timeout.
* Another first version is created, again with the old revision date (!), because the version is created before the record is saved.
* Next time you save, the version is deleted again and another first version is created; now with an up-to-date revision date.
* From there on, the versioning works as expected.

@contao/developers Any idea how to fix this?

**Comment by leofeyer** [comment] 2016-02-17 14:28
Except reverting the changes from #7730 of course ;)

**Comment by leofeyer** [comment] 2016-02-17 14:34
Never mind, reverting the changes is correct. Let's instead try to solve the initial problem as described here:

https://github.com/contao/core/issues/7730#issuecomment-99985674

**Comment by leofeyer** [comment] 2016-02-17 14:36
Fixed in bfdfd4f463717f0a75d9c99d65aa37f9ff3ad0ef.

**Closed by leofeyer** 2016-02-17 14:36 UTC
Labels: defect
