### ISSUE TITLE
PageSelector does not sort pages correctly when limited

### ISSUE THREAD

**Issue by Toflar** [contao/core#8577] opened 2016-11-22 12:46 UTC
When the page selector widget is limited by setting root nodes, the `sorting` is not considered.

**Comment by leofeyer** [comment] 2016-11-22 13:37
What kind of root nodes did you set? Just the ID of the root page or all IDs of all pages?

**Comment by Toflar** [comment] 2016-11-22 13:41
Changelanguage ;)

**Comment by leofeyer** [comment] 2016-12-13 16:20
That does not really help …

**Comment by leofeyer** [comment] 2016-12-13 16:29
https://github.com/terminal42/contao-changelanguage/blob/ad4269ece6918109cc4361bb4bf46a7fa9441ed7/library/Terminal42/ChangeLanguage/EventListener/DataContainer/PageInitializationListener.php#L117

**Comment by leofeyer** [comment] 2016-12-15 14:11
Hm, I struggle to reproduce the issue.

```php
// system/config/dcaconfig.php
$GLOBALS['TL_DCA']['tl_user']['fields']['pagemounts']['eval']['rootNodes'] = array(49, 48, 1);
```

Even if I change the order of the IDs (e.g. `array(48, 1, 49)`), the sorting of the page picker tree is always correct.

**Comment by leofeyer** [comment] 2016-12-15 14:51
The problem is that you are providing the IDs of all pages in the first level, which means you are setting different mounting points. If you instead provided just the ID of the root page, the problem would be solved:

```php
// Terminal42\ChangeLanguage\EventListener\DataContainer\PageInitializationListener:116
if (null !== $masterRoot) {
    $GLOBALS['TL_DCA']['tl_page']['fields']['languageMain']['eval']['rootNodes'] = $masterRoot->id;
}
```

**Comment by leofeyer** [comment] 2016-12-15 15:19
Fixed in 97cddae5de4d532fc444f6ec375dd913a4d62d2b. You should still add `ORDER BY sorting` to the SQL query in the `PageInitializationListener` class on line 117.

**Closed by leofeyer** 2016-12-15 15:19 UTC
Labels: defect
