### ISSUE TITLE
{{picture}} insert tag will not load the alternative text by default

### ISSUE THREAD

**Issue by rflx** [contao/core#8761] opened 2017-08-04 16:12 UTC
The `{{picture}}`-insert tag is not loading the alternative text which is set in the file manager for the image by default.

Btw. it works if you set the additional `alt` parameter to override it like this:
```{{picture::e9b6ede8-7926-11e7-af8e-01a8497672d9?alt=Foo bar}}```

Can someone reproduce this issue? Tested on Contao 4.4.2

**Comment by fritzmg** [comment] 2017-08-04 16:55
Duplicate of https://github.com/contao/core-bundle/issues/936

**Closed** 2017-08-04 18:21 UTC
Labels: duplicate
