### ISSUE TITLE
4.4: user login with error

### ISSUE THREAD

**Issue by jankout** [contao/core#8734] opened 2017-06-21 23:15 UTC
Hello, 

unfortunately, in one installation comes to an error when an user wants to log in. It does not matter when I make the user to administrator or add to a new created group later. 

This is the error message in the log file (var/logs).  

```
[2017-06-22 01:08:25] request.INFO: Matched route "contao_backend_login". {"route":"contao_backend_login","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::loginAction","_route":"contao_backend_login"},"request_uri":"http://www.cadus.org/contao/login","method":"POST"} []
[2017-06-22 01:08:25] security.INFO: Attempting SimplePreAuthentication. {"key":"backend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2017-06-22 01:08:25] app.CRITICAL: An exception occurred.  []
```
I think it depends on the _**uri**_ extension? Is it correct? 

Thank you.

**Comment by fritzmg** [comment] 2017-06-22 13:15
Full stack trace (truncated):
```
Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing 'UPDATE tl_user SET …, newscategories='a:1:{i:0;s:1:\"1\";}', … WHERE id='7'':

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'newscategories' at row 1

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
  at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception occurred while executing 'UPDATE tl_user SET …, newscategories='a:1:{i:0;s:1:\"1\";}', … WHERE id='7'':SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column \'newscategories\' at row 1', object(PDOException))
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128)
  at Doctrine\DBAL\DBALException::driverExceptionDuringQuery(object(Driver), object(PDOException), '…', array())
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855)
  at Doctrine\DBAL\Connection->executeQuery('…')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:284)
  at Contao\Database\Statement->query()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:257)
  at Contao\Database\Statement->execute('7')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/User.php:571)
  at Contao\User->save()
     (vendor/contao/core-bundle/src/Resources/contao/classes/BackendUser.php:336)
  at Contao\BackendUser->save()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/User.php:456)
  at Contao\User->login()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendIndex.php:39)
  at Contao\BackendIndex->__construct()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:67)
  at Contao\CoreBundle\Controller\BackendController->loginAction()
  at call_user_func_array(array(object(BackendController), 'loginAction'), array())
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:62)
```

**Comment by fritzmg** [comment] 2017-06-22 13:17
As mentioned in the forum, this is probably a bug within [BackendUser.php#L407-L412](https://github.com/contao/core-bundle/blob/4.4.0/src/Resources/contao/classes/BackendUser.php#L407-L412):
```php
// The new page/file picker can return integers instead of arrays, so use empty() instead of is_array() and StringUtil::deserialize(true) here
if (!empty($value))
{
	$this->$field = array_merge((is_array($this->$field) ? $this->$field : (($this->$field != '') ? array($this->$field) : array())), $value);
	$this->$field = array_unique($this->$field);
}
```
I think this means that, if there is a single checkbox, like `newscategories` from the news_categories extension (see [codefog/contao-news_categories/dca/tl_user.php#L24-L30](https://github.com/codefog/contao-news_categories/blob/2.8.3/dca/tl_user.php#L24-L30)) and it is checked, the data will be transformed into `array('1')`, instead of just `'1'` and this leads to the aforementioned error in the stack trace, because the SQL field is just a simple `char(1)`, which is sufficient for a single `checkbox` widget of course.

I'll make more tests and provide a full reproduction.

**Comment by fritzmg** [comment] 2017-06-22 17:17
## Reproduction

1. Add the following to `app/Resources/contao/dca/tl_user.php`:
```php
$GLOBALS['TL_DCA']['tl_user']['palettes']['extend'] .= ';{foo_legend},foo';
$GLOBALS['TL_DCA']['tl_user']['palettes']['custom'] .= ';{foo_legend},foo';

$GLOBALS['TL_DCA']['tl_user']['fields']['foo'] = array
(
    'exclude'                 => true,
    'inputType'               => 'checkbox',
    'sql'                     => "char(1) NOT NULL default ''"
);
```
2. Add the following to `app/Resources/contao/dca/tl_user_group.php`:
```php
$GLOBALS['TL_DCA']['tl_user_group']['palettes']['default'] .= ';{foo_legend},foo';

$GLOBALS['TL_DCA']['tl_user_group']['fields']['foo'] = array
(
	'exclude'                 => true,
    'inputType'               => 'checkbox',
    'sql'                     => "char(1) NOT NULL default ''"
);
```
3. Add the following to `app/Resources/contao/config/config.php`:
```php
$GLOBALS['TL_PERMISSIONS'][] = 'foo';
```
4. Create a new user group and enable `foo`.
5. Create a new user and assign the previously created user group.
6. Log out of the back-end.
7. Log into the back-end with the newly created user.

Now either one of the following things will happen, depending on your SQL server configuration:

* If your SQL server does not allow inserting data that is too long for the field, you will get a `Doctrine\DBAL\Exception\DriverException` with `An exception occurred while executing 'UPDATE tl_user SET …, foo='a:1:{i:0;s:1:\"1\";}', … WHERE id='7''`
* If your SQL server does allow inserting data that is too long for the field, the SQL server will simply truncate the data and no exception will occur. However the `tl_user.foo` field is filled with `a` instead of `1` for the logged in user.

## Cause

As suspected [BackendUser.php#L405-L412](https://github.com/contao/core-bundle/blob/4.4.0/src/Resources/contao/classes/BackendUser.php#L405-L412) transforms any field value from the group to an array, even for single checkboxes.

**Comment by aschempp** [comment] 2017-06-23 06:55
That is a long known behavior, permissions must be multiple fields. Also because otherwise they cannot be easily merged from groups etc. It works fine if you're not using a permission…

**Comment by jankout** [comment] 2017-06-23 07:00
What does it mean exactly? Should the developer of the extension improves something?

**Comment by aschempp** [comment] 2017-06-23 07:22
I think the extension needs to be changed because what it currently does will not work in Contao.

**Comment by fritzmg** [comment] 2017-06-23 07:58
> That is a long known behavior, permissions must be multiple fields.

Indeed, the behavior is the same in Contao 3.x as well.

> Also because otherwise they cannot be easily merged from groups etc.

Well, there is nothing that needs to be merged with a single checkbox. Either it is set or it is not. The inheritance type dictates what value the field in `tl_user` would be.

**Comment by qzminski** [comment] 2017-06-23 08:17
Please close this issue as it is related only to the news_categories extension.

**Closed** 2017-06-25 11:10 UTC
