### ISSUE TITLE
Page cache conflict when using both HTTP and HTTPS

### ISSUE THREAD

**Issue by KaiserCh** [contao/core#8672] opened 2017-03-21 09:23 UTC
When publishing a page both over HTTP and HTTPS (e.g. to accomodate to old non-SNI-clients; or to use the domain for Amazon Sellercentral CSV image uploads, which don't work over HTTPS), the page cache will make a huge mess. Whichever protocol is used for creating a cache file will determine, what type of URLs are created inside the file for CSS, JS,... So if any cached page is first called via HTTP and then via HTTPS, the HTTPS-page will be severely broken, containing unsecure scripts and styles.

To solve this problem, the $strCacheKey should contain the protocol used, resulting in 2 different cache files for the same URL but different access modes.

**Comment by fritzmg** [comment] 2017-03-21 09:47
Duplicate of #8531.

**Closed** 2017-03-21 10:56 UTC
