### ISSUE TITLE
Internal cache breaks for multiple extensions using the same classes in DCA files

### ISSUE THREAD

**Issue by ClaudioDeFacci** [contao/core#8635] opened 2017-01-28 16:44 UTC
Hi everyone,

I just had the issue that creating the internal cache failed after setting up several extensions that are using a class from a common helper extension.
The helper extension is set as a dependency for the other extensions - so this works fine.

Contao version: 3.5.24

## The setup is like this:

1. ExtensionA has class HelperClass in namespace ExtensionA\HelperClass
2. ExtensionB uses ExtensionA\HelperClass in a DCA config file like so:
```
use ExtensionA\HelperClass;
$variable = HelperClass::method();
```
3. ExtensionC uses ExtensionA\HelperClass in a DCA config file like so (same as ExtensionB):
```
use ExtensionA\HelperClass;
$variable = HelperClass::method();
```

## The problem:
As the internal cache seems to add all contents of the DCA files into one file the use statements get inserted multiple times.
This ofcourse causes the fatal error:
> Cannot use ExtensionA\HelperClass as HelperClass because the name is already in use in /var/www/exploreimpact.dev/web/system/cache/dca/tl_XYZ.php on line 1234

### My fast solution:
```
use ExtensionA\HelperClass as ExtensionB_HelperClass;
$variable = ExtensionB_HelperClass::method();

// ...
```

## What do you think about this behaviour?
Is this wanted?
Shouldn't the cache creation watch out for stuff like this?
Or did I miss a best practise on this?

I actually would not want to always use classes from other namespaces like that if there is no real name collision.
```
use X as Y;
```
I would expect a behaviour as know from i.e. normal autoloading.

Greetings
Claudio

**Comment by fritzmg** [comment] 2017-01-29 10:00
Duplicate of #8530

**Comment by leofeyer** [comment] 2017-01-31 19:54
@contao/developers Did we decide not to back port #8530?

**Comment by Toflar** [comment] 2017-01-31 22:29
Nope. Can be backported imho.

**Comment by discordier** [comment] 2017-02-01 03:58
In fact this should be back ported. I initially experienced this problem in Contao 3.5 also.

**Comment by leofeyer** [comment] 2017-02-02 14:32
Back ported in fb05043132ea5706fba3ed83aceb99f234d03455.

**Closed by leofeyer** 2017-02-02 14:32 UTC
Labels: defect
