### ISSUE TITLE
Is window.respimage call actually needed?

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7988] opened 2015-08-29 21:29 UTC
Due to [this thread](https://community.contao.org/de/showthread.php?58903-script-in-Template-picture_default-html5) I was wondering why

``` JavaScript
  <script>
    window.respimage && window.respimage({
      elements: [document.images[document.images.length - 1]]
    });
  </script>
```

in the [picture_default](https://github.com/contao/core/blob/3.5.2/system/modules/core/templates/picture/picture_default.html5) template is actually there at all. According to [the documentation of respimage](https://github.com/aFarkas/respimage#api) you only need this API function if you are loading new responsive image sets dynamically into the page - which by default Contao does not at any point, or am I mistaken?

Also this script is inserted for _every_ responsive image set and thus unnecessarily increases the file size of the page (and causes unnecessary computing time) if there happen to be a lot of images on one page (e.g. in a gallery).

**Comment by Metis77** [comment] 2015-08-30 14:04
Also this script is included even if respimg is disabled in the contaoffice template settings.

As for dynamical loading:
I think respimg should be initialized from the ajax complete event if needed.

**Comment by leofeyer** [comment] 2015-09-01 15:33
There is a reason why the script is injected after each image. @ausi Can you elaborate please?

**Comment by ausi** [comment] 2015-09-01 16:34
It is there to notify the respimage script as soon as possible and prevent a “flash of unreplaced images”.

> Also this script is inserted for every responsive image set and thus unnecessarily increases the file size of the page (and causes unnecessary computing time) if there happen to be a lot of images on one page (e.g. in a gallery).

Do you have data on how much the gzipped size of the HTML code increases and how much computing time it costs?

> Also this script is included even if respimg is disabled in the contao template settings.

The *picture_default* template doesn’t know about the layout settings. If the polyfill isn’t loaded the script does nothing, so it shouldn’t be a problem.

At the time we implemented the responsive images feature, almost no browser supported it and therefore it was important to prevent a “flash of unreplaced images” for all users. Once IE/Edge and Safari follow the other major browsers and support it too (they are working on it AFAIK), we should remove this script tag IMO.

**Comment by Metis77** [comment] 2015-09-01 19:59
I made some tests in Safari, ie11 and Edge.

## flash of unreplaced images
> It is there to notify the respimage script as soon as possible and prevent a “flash of unreplaced images”.

I could not see any “flash of unreplaced images”.
As images in Contao always have `width` and `height` attribute with the `img` tag, there should never be a  „reflow“ of the layout. 
As soon as an image is loaded (by default img src, srcset or by respimage) there will be a „repaint“. The repainting can not be avoided, as images are always loaded after the dom.ready.

On the other hand the initial load of a page is the most important.
Anything that is going on, should as fast as possible. 
```javascript
window.respimage&&window.respimage({elements:[document.images[document.images.length-1]]})
```
Initializing the plugin "respimage" for each picture will probably take some cpu time.


There are ways to increase the initial loading speed of images, that are in view. For excample with "lazysizes"


## two images loaded
lets asume this image with active polyfill:
```html
    <img 
        src="picture.img"
        srcset="
            picture_100w 100w,
            picture_300w 300w,
            picture_600w 600w
        "
        sizes="100vw"
    />
```

`srcset` may be there to deliver the best fitting picture and to save bandwidth.

If rendering this on a browser that does not support srcset, the src is simply loaded.
But if we use "respimages" to replace the src, a major issue is happening: <b>two images are loaded</b>, the first src and the replaced src.
There are solutions to this at the <a href="https://github.com/aFarkas/respimage/blob/gh-pages/README.md#user-content-known-issuescaveats" target="_blank">respimage readme.md</a>.

## solution
The best aproacht might be the "no-script" aproach, that is talked about <a href="https://github.com/aFarkas/lazysizes#user-content-the-noscript-pattern" target="_blank">here</a>. 
This will work with or without the polyfill respimage 
and with or without javascript enabled.

To make this work correctly:
- the picture_default template must know if the polyfill is active.
- `<html lang="de" class="no-js">` The class "no-js" must become part of the template and removed by inline script:
```javascript
(function(h){h.className = h.className.replace('no-js', '')})(document.documentElement)
```

Then the template output for active polyfill should be this:
```css
    .no-js .image_container > img.respimage {
        display: none;
    }
```

```html
<figure class="image_container">
    
    <!-- noscript pattern -->
    <noscript>
        <img src="picture.jpg" width height alt title />
    </noscript>

    <!-- data URI to prevent the unwanted initial load of the original src  -->
    <img class="respimage"
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
        srcset="
            picture_100w 100w,
            picture_300w 300w,
            picture_600w 600w
        "
        sizes="100vw"
        width height alt title
    />
</figure>
```


The template output with disabled polyfill shold be this, as usual:
```html
<figure class="image_container">
    <img
        src="picture.jpg" 
        srcset="
            picture_100w 100w,
            picture_300w 300w,
            picture_600w 600w
        "
        sizes="100vw"
        width height alt title
    />
</figure>

```




Well this was a lot of writing.
Hopefully anybody will read and hopefully Leo will consider this. 

I am convinced, that this is a way faster and bullet prove aproach.

**Comment by ausi** [comment] 2015-09-02 11:35
> I could not see any “flash of unreplaced images”.

I just tested it in Safari 8, iOS 8.4 and IE11 saw a “flash of unreplaced images” without the `<script>` tag in the template.

> As images in Contao always have `width` and `height` attribute with the `img` tag, there should never be a „reflow“ of the layout.

Thats not true, if you use a responsive image with `<source>` tags or the `sizes` attribute no `width` and `height` attributes will be there, see also #7500. Even if `width` and `height` attributes are there, it will trigger a reflow on sites which use responsive CSS like `img { width: 100%; height auto }`.

> Initializing the plugin "respimage" for each picture will probably take some cpu time.

Do you have more information about why calling `respimage` for each picture takes more cpu time than calling it on DOM ready for all images?

> But if we use "respimages" to replace the src, a major issue is happening: two images are loaded, the first src and the replaced src.

respimage is optimized for this case and only loads the second image if it’s necessary, that was one reason why we chose respimage instead of picturefill. See also https://github.com/aFarkas/respimage/issues/37#issuecomment-85083468 and #7369.

**Comment by Metis77** [comment] 2015-09-02 14:29
>I just tested it in Safari 8, iOS 8.4 and IE11 saw a “flash of unreplaced images” without the `<script>` tag in the template.

I never heard a “flash of unreplaced images”. 
And I can not reproduce it, when the script in question is disabled.
Can you see it on this <a href="http://contao.derhaeuptling.com/" target="_blank">Contao Demo</a>.

The only thing I can see, is the ordinary repaint, when the image is loaded. 

The suggestion I made above would prevent this flash anyway, as it would not load two images.

>Do you have more information about why calling respimage for each picture takes more cpu time than calling it on DOM ready for all images?

![bildschirmfoto 2015-09-02 um 16 12 06](https://cloud.githubusercontent.com/assets/1408361/9633498/958a2a04-518d-11e5-9bf7-4153aa0ef438.png)

The fist 4 marked lines are caused by the inline script.
The last marked line is where respimage would do its job normally.

Indeed the inline script method forces to load ALL images way earlier and reduces the runtime of original respimage init (last mark). 
If you have lots of images the time this inline scrips are running will stack ...

Forcing ALL images to load an window.ready may also not be a good idea.
They will block each other, espacially if there are more images.

If the perceived performance is what this is about, the first / inview  images should be loaded first.
[LazySizes](https://github.com/aFarkas/lazysizes) is sugested by "respimges" makers and is doing a great job loading the inview images first.
But that might be another topic.

What do you think of my suggestion, above?
Don't you think it would prevent the loading of two images and give the possibility to avoid the inline script?

**Comment by ausi** [comment] 2015-09-02 16:18
> I never heard a “flash of unreplaced images”.

Maybe you heard of “[flash of unstyled content (FOUC)](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)” or “[flash of unstyled text (FOUT)](http://www.paulirish.com/2009/fighting-the-font-face-fout/)”, it means the same but for images that change after the page was already shown to the user. But maybe I’m the only one using that term :)

> Can you see it on this [Contao Demo](http://contao.derhaeuptling.com/).

Yes, with Safari 8.0.7 (empty cache and throttled network) a low resolution image is shown first and gets switched with a better image. But in this demo the size is fixed via CSS and the proportion stays the same so the effect is not really bad. If you use the `<picture>` tag with different zoom levels and proportions the “flash of unreplaced images” would be much worse.

> Indeed the inline script method forces to load ALL images way earlier and reduces the runtime of original respimage init (last mark).

So we don’t know if it would be faster without the `<script>`s after each image. It may also depend on the browser.

> What do you think of my suggestion, above?

I don’t like the `<noscript>` approach. What if the JavaScript on the page fails? All images would be missing then.

Because all images are generated via the *picture_default* template it’s very easy to change the behavior for your project or to create an extension that changes the template. I would like to keep it simple and robust in Contao itself. As already said: Once IE/Edge and Safari support `<picture>` we should remove this script tag.

**Comment by fritzmg** [comment] 2015-09-24 20:54
I see now why it is needed, but haven't had time yet to make a more in depth test on how much this can affect browser performance and bloat the HTML (say, on a Contao page with a galery content element with 100 pictures).

But at least this ticket can serve as a reference for a possible optimization, if someone ever notices significant negative effects in such cases.

**Comment by CMSworker** [comment] 2018-08-08 22:15
3 years later now... I think this "issue" could be reopened now for Contao 4.6/4.7?

I stumbled upon this script on a gallery page with over 250 thumbnails... and think the many added script lines are ...well ...MANY MANY additional code lines ("don't repeat yourself" came to my mind :wink: )

[https://caniuse.com/#feat=picture](https://caniuse.com/#feat=picture)

IE was "replaced" by Edge in 2015 and Edge is supporting the picture element since November 2015.

Safari is supporting the picture element since march 2016.

Only problem is that Internet Explorer is part of the windows operating system. Version 11 was released in 2013 – because of Edge, IE probably won't receive new features anymore. Caniuse says global usage of IE11 is 2,64%. I think the script could be removed from the pixture.html5-template now. Those 2,64% people might see a "flash of unstyled content" but 2,64% is a small minority...

Second reason, why I'm voting to remove the inline script: Bringing Contao slowly closer to a possible usage of [content security policy](https://www.google.com/search?q=Content+Security+Policy)... (at least for the frontend – for backend this is probably a much bigger task, didn't check that)

**Comment by Metis77** [comment] 2018-08-08 22:37
@CMSworker maybe this helps for now: https://github.com/derhaeuptling/contao-lazy-images .
This Repo also contains the performance improvements I suggested above.

**Comment by ausi** [comment] 2018-08-09 04:24
I agree. We can remove the script now from the *picture_default.html5* template.

**Comment by fritzmg** [comment] 2018-08-09 07:21
The script is only needed anyway if you enable the polyfill in the page layout. May be the script should be wrapped in an
```php
<?php if (…): ?>
  …
<?php endif; ?>
```
where we check whether the polyfill is actually enabled? Though that would cause a lot of PHP checks on pages with a lot of images of course.

**Comment by Metis77** [comment] 2018-08-09 07:59
I would favor to remove it completely.

**Comment by leofeyer** [comment] 2018-08-09 09:14
@ausi Do we need to backport this to Contao 4.4 as well?

**Comment by leofeyer** [comment] 2018-08-09 11:27
Removed in contao/core-bundle@9fb933881b1e2da6c71e6de3dab3df9c2f161ee7.

**Closed by leofeyer** 2018-08-09 11:27 UTC
Labels: defect

**Comment by ausi** [comment] 2018-08-09 17:59
> Do we need to backport this to Contao 4.4 as well?

I don’t think so. I would not expect such changes in a bugfix release.

**Comment by leofeyer** [comment] 2018-08-10 07:07
Agreed.
