### ISSUE TITLE
No swipe on iframe (slider, youtube)

### ISSUE THREAD

**Issue by Aybee** [contao/core#8581] opened 2016-11-30 14:53 UTC
**Online-Demo**:
Copy the element YouTube on "Content Elements - Media elements" and paste is into "Home - slider".

Now you will see on smartphone, that you can not swipe.

**Comment by leofeyer** [comment] 2016-12-20 08:14
I'm not sure if this can be fixed. BTW, you can actually swipe if you touch something else than the iframe (e.g. the headline). Maybe @aschempp @JanoschSkuplik can shed some light on this?

**Comment by aschempp** [comment] 2016-12-20 08:30
Works fine for me. What device are you on? And where exactly did you paste it? Into the slider or after the slider or before the slider?

**Comment by leofeyer** [comment] 2016-12-20 08:34
It really works for you? On your iPhone? Because I could definitely reproduce it. You have to copy the YouTube content element into the slider (third item in my test setup) and then try to swipe **with your finger on the iframe**, not on the headline or another element from the main frame.

**Comment by aschempp** [comment] 2016-12-20 08:40
ok I see the issue now. Well it *could* be solved by placing an element above the iframe, but I really don't think we want to implement that…

**Comment by leofeyer** [comment] 2016-12-20 08:44
Me neither.

**Comment by JanoschOltmanns** [comment] 2016-12-20 09:08
I think, it's an issue of swipe: https://github.com/thebird/Swipe/issues/36

**Comment by fritzmg** [comment] 2016-12-20 11:03
@JanoschOltmanns the solution by @qnp there also involves adding a transparent layer over the iframe (not covering the control elements).

I don't think this is something that can or should be solved by Contao. If you use iframes inside a slider (any slider) you must realize that any input action on the iframe goes to the iframe of course.

**Comment by leofeyer** [comment] 2017-08-10 14:50
This is what the Swipe developer said:

> Hey guys really good convo here. I played with some of the examples and don't really see any simple solutions off hand. If you find anything let me know :)

So I'm closing the issue.

**Closed by leofeyer** 2017-08-10 14:50 UTC
Labels: defect, up for discussion

**Comment by Aybee** [comment] 2017-08-12 20:06
Thank you, that's ok for me. I think we have to offer some kind of extra area in our theme where we can touch with a finger to slide an iframe video if we want to.
