### ISSUE TITLE
3.4.0 datepicker field validation

### ISSUE THREAD

**Issue by bcat-eu** [contao/core#7498] opened 2014-12-04 11:20 UTC
Online Demo:

1. In Settings set Date format to "d-m-Y" (leave default Date and time format)
2. Go to any element or article and under "publish settings" try to set date from or date to to any day / time in October. You'll get the error "Invalid date "2014-10-10 12:08"!". 

As far as I can tell it doesn't have problems with other months.

Only happens since 3.4.0, 3.3 worked with the same settings.

An easy solution would be to set both "Date" and "Date and time" to the same d-m-Y or Y-m-d, still the October + 3.4.0 issue seems weird enough to look into.

**Comment by leofeyer** [comment] 2015-01-16 15:15
How do I reproduce this in the online demo?

**Comment by bcat-eu** [comment] 2015-01-16 17:53
At the time I wrote the ticket as follows.

Online Demo:

* In Settings set Date format to "d-m-Y" (leave default Date and time
format)

* Go to any element or article and under "publish settings" try to set date
from or date to to any day / time in October. You'll get the error "Invalid
date "2014-10-10 12:08"!".

As far as I can tell it doesn't have problems with other months.

Also see the suggested fix.

**Comment by leofeyer** [comment] 2015-01-20 12:55
Yes, that is because the "publish" settings use the *date and time* format and not just the date format.

**Comment by bcat-eu** [comment] 2015-01-20 13:15
@leofeyer it's not about "publish" settings, but rather the dateToUnix function. 
case 'datim' that does not comply with system settings for datim so the user has to change both datim and date settings for them to always work. Solved easily by passing current datimFormat setting as mentioned above

**Comment by leofeyer** [comment] 2015-01-20 15:44
I stumbled upon the issue while trying to fix #7471. Fixed in 6a8616717e1da6674a4be23ee28911f31bcc136b now.

**Closed by leofeyer** 2015-01-20 15:44 UTC
