### ISSUE TITLE
Inconsistent form css ID when page cache is enabled 

### ISSUE THREAD

**Issue by tsarma** [contao/core#8538] opened 2016-10-20 15:49 UTC
As mentioned here: https://github.com/contao/core/commit/ec9c8847965add2eccc0f810a4554093020434aa#commitcomment-19503920

> It can be reproduce in online demo: Enable page cache 
> 1- Make a form and give it a css ID
> 2- Make a module of type custom HTML -> {{insert_form::6}} , where 6 is the id number of form.
> 3- Place the module on the page.

When page cache is enabled, form css ID is appended with form's id number, the behaviour exhibits only on the first time page load. On reload this does not happen.

**Comment by leofeyer** [comment] 2016-10-24 10:14
I have tried to reproduce the issue with the Contao Official Demo.

I have added a HTML element on the "Applications" page right below the form element and I have inserted the form a second time via `{{insert_form::5}}`. The form has the CSS ID `contact`.

The first time the page is called (no cached version available), the forms get `id="contact"` and `id="contact_3"`, whereas in the page cache, they correctly have `id="contact"` and `id="contact_2"`. If the page is then loaded from the cache, the IDs are correct.

So there is a problem, but it does not seem to be your initial problem:

> I have a form with css id, for example "myformid", With addition of changes above, it adds string '_2' to my form's id attribute and it becomes "myformid_2". Because of that, all css rules #myformid {} for the form is not working. But on reload of the same page, form's id attribute is as expected "myformid", and css rules are applied as defined.

What exactly did you do to trigger the error?

**Comment by fritzmg** [comment] 2016-10-24 10:43
I was able to reproduce it with his reproduction steps.

1. log into the Contao demo.
2. enable the page cache in the website root (set it to 30 days for example).
3. create a new form and give it the CSS ID `test`. Insert a simple text field with submit button as well. 
4. create a new module of the type `html`.
5. insert `{{insert_form::6}}` into the HTML module. Replace `6` with the form's actual ID, if necessary.
6. go to _Articles_ and edit the the _Home_ article of the _Home_ page.
7. Insert a new content element of the type _Includes_ » _Module_.
8. Choose the previously created HTML module.
9. Clear the page cache under _System_ » _Maintenance_.
10. log out of the Backend or open a private browing window.
11. open the home page in the frontend.

The form will have the CSS ID `test_2` instead of `test`.

**Comment by leofeyer** [comment] 2016-10-24 12:40
Ok, so obviously `replaceInsertTags()` is run twice in this case, one time to generate the cache content and another time to generate the page content. Unfortunately, the form usage counter is not reset.

@contao/developers /cc

**Comment by leofeyer** [comment] 2016-12-14 15:46
As discussed in Mumble on December 14th, there is no way to solve this, except omitting the CSS ID altogether. Therefore, we want to revert #7643 in Contao 3 and remove the automatic form CSS ID assignment in Contao 4.

@amenk /cc

**Comment by leofeyer** [comment] 2016-12-15 13:53
Reverted in 8a52331f7c1b90636e44b35aa9da98c57895e990.

**Comment by leofeyer** [comment] 2017-01-06 08:34
It is actually not that easy to remove the CSS ID. First, the [error focus script](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/forms/form_wrapper.html5#L26) needs an ID and second, the problem is not limited to the form generator. Almost every module that generates a form also assigns a CSS ID, so as soon as they are included more than once, …

**Comment by aschempp** [comment] 2017-01-06 12:05
the error focus script could target the `FORM_SUBMIT` as well 😃

**Comment by aschempp** [comment] 2017-01-06 12:06
btw, this looks like MooTools code?

**Comment by leofeyer** [comment] 2017-01-06 12:15
You mean `$$('input[type="hidden"][value="<?php echo $this->formSubmit; ?>"]').getParent('form')`???

**Comment by aschempp** [comment] 2017-01-06 12:20
jup. the `type=hidden` is unnecessary, if anything I'd go for the field name, but not necessary either.

**Comment by aschempp** [comment] 2017-01-06 12:23
actually it's probably not necessary to check the form at all, because there won't be multiple `p.error`. A vanilla selector like `document.querySelector('form p.error')` should be enough anyway.

**Comment by leofeyer** [comment] 2017-01-06 12:42
> because there won't be multiple `p.error`

How do you know?

**Comment by aschempp** [comment] 2017-01-06 12:43
First of all, it's extremely unlikely to have multiple forms with errors. If that would be the case, there would be multiple scroll-to scripts which can't work anyway.

**Comment by Toflar** [comment] 2017-01-07 12:24
I agree with @aschempp

**Comment by leofeyer** [comment] 2017-01-09 08:53
But a general selector does not make sense in the `form_wrapper` template, does it? It would probably need to go into the `fe_page` template.

**Comment by Toflar** [comment] 2017-01-09 08:58
Imho should be included like e.g. the gallery scripts via `$GLOBALS['TL_whatever']` in the template.

**Comment by aschempp** [comment] 2017-01-09 09:30
@leofeyer why not, because of a potential duplicate? who cares?

@Toflar why would that make a difference?

**Comment by Toflar** [comment] 2017-01-09 09:32
Would not be included twice then :) If it's included twice it will be evaluated twice which probably doesn't cause any issues but is not clean anyway.

**Comment by leofeyer** [comment] 2017-07-17 14:44
Fixed in Contao 4.4 in contao/core-bundle@bd3c74904293cf32deac821ac7b6506b248f5f1b and contao/installation-bundle@4ea804bed3731c42a812030ae473bbbb56b2dd35.

**Closed by leofeyer** 2017-07-17 14:44 UTC
Labels: defect
