### ISSUE TITLE
page cache circumvents maintenance mode

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8804] opened 2017-10-23 13:48 UTC
Tested in Contao 3.5.31.

### Reproduction

1. Enable the page cache for a single page - e.g. `example.org/foo.html`.
2. Log out of the back end.
3. Open `example.org/foo.html` in the front end.
4. Log into the back end.
5. Enable the maintenance mode.
6. Log out of the back end.
7. Clear the browser cache.
8. Open `example.org/foo.html` in the front end.

You will see the page instead of the maintenance notice. Any non-cached URL will show the maintenance notice while any cached URL will show the cached page instead.

**Comment by aschempp** [comment] 2017-10-24 12:11
That's most likely your browser cache?

**Comment by aschempp** [comment] 2017-10-24 12:11
Or maybe AppCache … ?

**Comment by fritzmg** [comment] 2017-10-24 12:26
> That's most likely your browser cache?

I cleared it while observing this.

> Or maybe AppCache … ?

Do you mean the page cache? Or the Symfony AppCache? This is a bug report for Contao 3, not 4 ;). I haven't checked in Contao 4.

**Comment by ausi** [comment] 2017-10-25 12:45
I was not able to reproduce this with Contao 3.5.30. Does this happen in multiple browsers?

**Comment by fritzmg** [comment] 2017-11-19 13:00
It's actually caused by the page cache. So if `example.org/en` and/or `example.org/de` are present in the page cache, those URLs will be served directly from the page cache, instead of showing the maintenance notice.

**Comment by fritzmg** [comment] 2017-11-19 20:52
Reproduction updated. Though I wonder if this is a known limitation.

**Comment by aschempp** [comment] 2017-11-20 20:22
I think we need to (and should) find another maintenance solution sometime. Lexik does not support what we need …

**Comment by ausi** [comment] 2017-11-20 23:19
@aschempp How is this issue related to the Lexik maintenance bundle?  
It is about the maintenance mode and the page cache in Contao 3.5.

**Comment by aschempp** [comment] 2017-11-21 19:39
Lexik Maintenance is running as kernel listener, that's why the page cache bypasses it. It also means the application has to be bootable, which was not the case with Contao 3. I think we should build our own solution that triggers way earlier...

**Comment by KaiserCh** [comment] 2017-11-23 14:35
Well, the reason for this behaviour is at least clear. The constructor for FrontendIndex calls outputFromCache before testing for the maintenanceMode variable.
Wouldn't is suffice to move the "if (!$_SESSION['DISABLE_CACHE'])" - block at the beginning of the constructor? Or am I missing something about the $_SESSION variable?

**Comment by leofeyer** [comment] 2018-04-11 07:09
Does this issue still occur in Contao 4.5 now that we have header replay?

**Comment by fritzmg** [comment] 2018-04-11 11:52
No, this issue does not occur in Contao 4.5.

**Comment by leofeyer** [comment] 2018-04-11 12:12
Ok, then I'm closing the issue. We cannot really fix it in Contao 3.5.

**Closed by leofeyer** 2018-04-11 12:12 UTC
Labels: defect
