### ISSUE TITLE
Keine youtube videos mehr im FF 44

### ISSUE THREAD

**Issue by Aybee** [contao/core#8217] opened 2016-02-10 12:13 UTC
Demo: http://demo.contao.org/en/media-elements.html
Auf dieser Seite laufen die Videos nicht mehr (Win 10 Firefox 44.0 u. 44.0.1)

siehe auch Forum: https://community.contao.org/de/showthread.php?60955-Youtube-Videos-funktionieren-in-Firefox-nicht-mehr

**Comment by fritzmg** [comment] 2016-02-10 13:36
We need to wait until there is a new `MediaElement.js` release that includes the fix - or hotfix it without it?

Though I would vote to ditch `MediaElement.js` + `<video>` in general for the YouTube Video Content Element and only use an `<iframe>` in general. This would however be a BC break, I guess.

I plan to release an extension that replaces the default `ce_player` template and uses the `<iframe>` and it would extend the existing DCA for the youtube element to incorporate all or some of the available [player parameters](https://developers.google.com/youtube/player_parameters).

**Comment by Aybee** [comment] 2016-02-10 22:26
Video runs if I dissable the Flash-Player plugin in FF. But Video did not fill the entire video box.
![capture_02102016_225249](https://cloud.githubusercontent.com/assets/1143013/12963933/9df7f902-d04d-11e5-97bb-937ff5c540f3.png)

**Comment by jenda77** [comment] 2016-02-11 11:07
I can confirm this behaviour but only on PC, on Mac it works. This issue concerns Internet Explover too.

**Comment by fritzmg** [comment] 2016-02-12 08:43
For anyone interested: I have released an extension that implements the YouTube element via `<iframe>` instead of the `<video>` element:

* ER2: [[youtube_iframe](https://contao.org/de/erweiterungsliste/view/youtube_iframe.de.html)]
* Packagist: [fritzmg/contao-youtube-iframe](https://packagist.org/packages/fritzmg/contao-youtube-iframe)
* GitHub: [fritzmg/contao-youtube-iframe](https://github.com/fritzmg/contao-youtube-iframe)

**Comment by fbender** [comment] 2016-02-16 11:58
> Though I would vote to ditch MediaElement.js + <video> in general for the YouTube Video Content Element and only use an <iframe> in general. This would however be a BC break, I guess.

I agree, Contao Core should only use the IFRAME methods of the different providers, they are way more reliable (and require less code thus smaller core). Extensions can then use mediaelement.js or similar for advanced players (e.g. with custom controls).

**Comment by fritzmg** [comment] 2016-02-16 12:35
Well, version `2.20.0` of MediaElement.js will prioritize `<iframe>` embedding for YouTube videos over Flash embedding anyway.

**Comment by fritzmg** [comment] 2016-02-16 12:38
Until `2.20.0` is finally released, this could also be integrated as a hotfix in Contao by manually changing the `mediaelement-and-player.js`. See https://github.com/johndyer/mediaelement/commit/5227a0f2b3957f6eca5387a0ce39796a756ba0d9

**Comment by leofeyer** [comment] 2016-02-19 10:54
I have updated the plugin to version 2.19.0.1 with the changes from johndyer/mediaelement@5227a0f2b3957f6eca5387a0ce39796a756ba0d9 in 902d37ee5547acad6874c8aadb5449a048f321c9. Can you please test if this solves the issue?

**Comment by leofeyer** [comment] 2016-02-19 11:00
The problem described in https://github.com/contao/core/issues/8217#issuecomment-182606828 is caused by the `<iframe>` tag not having the `style="width:100%;height:100%"` attribute, which is added to the `<video>` tag in the template. This is going to be a problem I guess.

**Comment by fritzmg** [comment] 2016-02-19 11:08
Hm, I'd say that things like that should be accounted for by your own CSS. Contao could integrate
```css
.mejs-mediaelement iframe {
    width:100%;
    height:100%;
}
```
in its CSS framework.

**Comment by leofeyer** [comment] 2016-02-19 11:59
I'm finally closing the ticket, because the update solves the initial problem. The "responsiveness" of the player is something that has been added in the Contao Official Demo and needs to be solved there.

**Closed by leofeyer** 2016-02-19 11:59 UTC
Labels: defect

**Comment by leofeyer** [comment] 2016-02-19 12:02
@fritzmg Your CSS fix works, however, it fixes something that is not supported by the core. The COD uses a modified template to add the `style` attribute and it needs to add the CSS fix, too.

**Comment by leofeyer** [comment] 2016-02-19 12:47
I have pushed the changes to the wrong branch, so the update is now in 9f9e650f3e33f0887c247596785ac43155b72140.
