### ISSUE TITLE
Contao Version does not show up in Contao backend?

### ISSUE THREAD

**Issue by codiso** [contao/core#8723] opened 2017-06-02 18:48 UTC
In Contao 3.x there was allways a possibility to see which version is uo and running.
In Contao 4 I can not see which version is installed. Would be nice to have that feature again.

**Comment by fritzmg** [comment] 2017-06-02 18:49
Duplicate of https://github.com/contao/core-bundle/issues/493

**Closed** 2017-06-02 19:14 UTC
