### ISSUE TITLE
standardize fieldnames

### ISSUE THREAD

**Issue by timgatzky** [contao/core#8403] opened 2016-07-11 13:08 UTC
Hi,
field names should be standardized on save by default to avoid spaces or any letter that might cause trouble later on.

**Comment by discordier** [comment] 2016-07-12 04:28
I have no idea what you mean. Can you post a real world code example?

**Comment by ADoebeling** [comment] 2016-07-12 05:33
Maybe @timgatzky was talking about "file names", uploaded by the file manager?

**Comment by timgatzky** [comment] 2016-07-12 06:29
regular field names

![Screenshot](http://www.tim-gatzky.de/screenshot_1296.jpg)

**Comment by timgatzky** [comment] 2016-07-12 06:33
I give a +1 to file names also!

**Comment by ADoebeling** [comment] 2016-07-12 06:35
Ahh, you're talking about the form generator. Yes, that seems to be a bug, even if I didn't tried to reproduce.

**Comment by Aybee** [comment] 2016-07-12 11:13
:+1: fieldnames and filenames
But I think we should accept the underscore.

**Comment by fritzmg** [comment] 2016-07-14 09:44
See also #8400

**Comment by timgatzky** [comment] 2016-07-14 09:45
jup. refers to the same problem. standardize field names on save and all be fine :)

**Comment by leofeyer** [comment] 2016-07-14 12:31
I guess we also need `[]` for array fields, so I think it should be:

```
A-Za-z0-9[]_-
```

@contao/developers Which characters should we allow?

**Comment by aschempp** [comment] 2016-07-14 12:32
do we really support manually creating array of fields? Does that currently work?

**Comment by Toflar** [comment] 2016-07-14 12:41
Just for the record: Full ASCII (so spaces too) are perfectly valid in a "name" attribute. Here's an excerpt of the HTML specification:

> The "get" method restricts form data set values to ASCII characters. Only the "post" method (with enctype="multipart/form-data") is specified to cover the entire [ISO10646] character set.

But I'm fine with restricting it to alphanumerics plus `_` and `-`.

**Comment by leofeyer** [comment] 2016-07-14 12:46
@aschempp Yes, and AFAIR you have added this feature. 😄

**Comment by leofeyer** [comment] 2016-07-14 12:48
I am referring to this: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Widget.php#L831-L832

**Comment by leofeyer** [comment] 2016-07-14 12:49
@Toflar You are right, but some browsers replace special characters such as dot or white space with `_` and `+`.

**Comment by timgatzky** [comment] 2016-07-14 13:21
Problems might not occurin the name attribute of the html element but in the POST/GET variables

**Comment by leofeyer** [comment] 2016-07-21 13:31
As discussed in Mumble on July 21st, we want to add a new method `Validator::isFieldName()`, which allows `A-Za-z0-9[]_-`. `Widget::validator()` needs to be extended with `'rgxp' => 'fieldname'`.

**Comment by timgatzky** [comment] 2016-07-22 08:35
[] should not be valid! 

Incase you have 2 form fields:
![Screenshot](http://www.tim-gatzky.de/screenshot_1319.jpg)

Frontend:
![Screenshot](http://www.tim-gatzky.de/screenshot_1323.jpg)

The second one will overwrite the value of the first one.

prints in $_POST
![Screenshot](http://www.tim-gatzky.de/screenshot_1322.jpg)

In POST variables the brackets will be ignored anyways. So leave that out. Brackets can only be valid for multiple GET parameters.

In addition: Field names should be unique inside the form

**Comment by ausi** [comment] 2016-07-22 09:31
> In POST variables the brackets will be ignored anyways. So leave that out. Brackets can only be valid for multiple GET parameters.

I don’t think that is true. I just tested it with this sample page:

```html+php
<pre><?php var_export($_POST); ?></pre>
<form action="" method="post">
	<input name="foo[]" value="bar">
	<input name="foo[]" value="baz">
	<button type="submit">submit</button>
</form>
```

**Comment by timgatzky** [comment] 2016-07-22 09:56
Sorry, wrong screenshot of the backend. Run your test with a fields name like:
1. myField[]
2. myField

Anyways. Just run a standardize over the field name value in a save_callback for that field and all is good. I don't even see a need for a validation.

**Comment by leofeyer** [comment] 2016-07-22 10:02
> Sorry, wrong screenshot of the backend. Run your test with a fields name like:
> 1. myField[]
> 2. myField

That's a configuration error IMHO.

**Comment by timgatzky** [comment] 2016-07-22 10:06
It's completely valid. See this as an example. I think field names should not contain brackets and should be tested unique against other field names in the same form.

**Comment by leofeyer** [comment] 2016-07-22 10:10
-1

Because the following is a valid configuration:

1. myField[0]
2. myField[1]

And there is no reason not to support this.

**Comment by timgatzky** [comment] 2016-07-22 10:20
> myField[0]
> myField[1]
> 

Ok, that will work. It kinda scares me to see array keys like this. But true, that is a configuration thing

**Comment by discordier** [comment] 2016-07-24 06:56
We must keep the brackets, otherwise we will break every wizard field.

**Comment by aschempp** [comment] 2016-07-24 08:16
@discordier you're confusing general input support with the input field in the Contao form manager.

**Comment by aschempp** [comment] 2016-07-24 08:18
I also like the idea of duplicate validation, l've seen that mistake and confusion before.

**Comment by Toflar** [comment] 2016-07-24 08:29
Imho [] should be allowed but stripped on duplicate validation which means the myField and myField[] mistake cannot happen :)

**Comment by discordier** [comment] 2016-07-27 01:50
Should be fine for me, will have to wait for the final implementation, maybe I have other concerns then but currently it looks like it should work out fine.

**Comment by leofeyer** [comment] 2016-08-15 15:37
Fixed in 32225128ee510637b1b1ee98ef81b03d1866e3c9.

**Closed by leofeyer** 2016-08-15 15:37 UTC
Labels: defect

**Comment by havutcuoglu** [comment] 2018-01-24 12:35
I think it's better to change the name of the form field
from:
Please enter only the following characters: A-Z0-9[]\_-
to:
Please enter only the following characters: A-Z0-9[]\_- Not allowed are Ö,ö,Ü,ü,Ä,ä,ß and spaces

The user doesn't understand the meaning of A-Z because in german you have between A-Z also the Ä,Ö,Ü etc. or we need to but standardize and change all character from 'ä' to 'ae' like space with '_'

![bildschirmfoto 2018-01-24 um 13 29 56](https://user-images.githubusercontent.com/11348417/35332361-033a6e90-010b-11e8-9233-f1cd1a0955b8.png)

**Comment by ausi** [comment] 2018-01-24 13:32
> The user doesn't understand the meaning of A-Z because in german you have between A-Z also the Ä,Ö,Ü etc.

I don’t think that the Umlauts are between A and Z in the german alphabet: <https://de.wikipedia.org/wiki/Deutsches_Alphabet>

**Comment by havutcuoglu** [comment] 2018-01-24 14:05
You are very funny. But you must understand that not all people are smart like you and me. 😃 
However, I think different.

**Comment by Toflar** [comment] 2018-01-24 14:27
> However, I think different.

If you do so, feel free to adjust the language files. I'm with @ausi: no change required here.

**Comment by Aybee** [comment] 2018-01-24 17:26
@ausi LOL that was what I liked to answer.

I think we should use
`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789[]_-`
No, not seriously 😉 😆 😊

**Comment by havutcuoglu** [comment] 2018-01-26 14:29
Hey guys, ok forget the (Umlaut) letters but here existing a other problem.

If you duplicate a form field add Contao automatically the (Kopie) on field name, but it's only A-Z0-9[]\_-  allowed.
I think here is something wrong.
Testet on Contao v3.5.31

And also in Contao v4.4.7 by duplicating a form field stay the field name unchanged but here add Contao as label the (Kopie) with parentheses. More than one textfield with the same name attribute is strange.

Contao v3.5.31
![bildschirmfoto 2018-01-24 um 13 29 56](https://user-images.githubusercontent.com/11348417/35443840-c657c9a2-02ac-11e8-923e-15c9ea8b0d83.png)

Contao v4.4.7
![bildschirmfoto 2018-01-26 um 15 18 24](https://user-images.githubusercontent.com/11348417/35443849-cc14b404-02ac-11e8-8838-6d7f567982df.png)
