### ISSUE TITLE
Member Password Reset

### ISSUE THREAD

**Issue by rburch** [contao/core#7698] opened 2015-03-18 13:58 UTC
There isn't a way to force a member to reset their password like you can with a user. Is this something you think might be good to add to the core?

**Comment by fiedsch** [comment] 2015-03-18 17:20
you could create a member with a random password you immediately forget. Then you tell her/him to use the "forgot password" function. This way a new password has to be set.

**Comment by rburch** [comment] 2015-03-19 00:14
That would work on an individual basis, but I’d like to be able to do it on a larger scale and switch with an edit multiple. Just seems like if the user has it why not have it on the members too. I look sfor an extension that would add it but didn’t see anything.


Bob Burch

Bright Cloud Studio
102 Elm Street, Suite 4 
Westfield MA 01085

413.885.0378
bob@brightcloudstudio.com <mailto:bob@brightcloudstudio.com>
brightcloudstudio.com <http://www.brightcloudstudio.com/>
facebook <https://www.facebook.com/brightcloudstudio>

**Comment by fiedsch** [comment] 2015-03-19 05:56
Sorry I was assuming you meant new members. Then this would be my process. In your case I would work on the database directly. But that only fixes half of the problem as the member has to be informed somehow.

**Comment by aschempp** [comment] 2015-03-19 08:14
Duplicate of #6304

**Closed** 2015-03-19 08:26 UTC
Labels: duplicate
