### ISSUE TITLE
Bug with recursive insert tag replacing when using the page cache

### ISSUE THREAD

**Issue by fritzmg** [contao/core#7700] opened 2015-03-18 17:38 UTC
### Summary

There is a bug in Contao 3.4.4 that causes insert tags not being replaced recursively, if you activated the page cache in Contao and the page is generated for the first time (i.e. not loaded from the cache). 

### Reproduction steps in the Official Contao Demo

* Create a new article anywhere
* In this article, create a new text element with this insert tag for example: `{{date::Y}}`
* Create a new HTML module and insert the newly created article: `{{insert_article::*}}`
* Add the newly created HTML module to a page layout, e.g. the header in the demo
* Activate the page cache
* Open the website in the frontend - with a browser that does not have an active backend login session, so that the page is generated for the page cache

### Expected behaviour

You should see `2015` where you inserted the module (which inserts the article, which has a content element with the insert tag `{{date::Y}}`)

### Observed behaviour

You see the insert tag instead: `{{date::Y}}`. When you load the page a second time, so that it is loaded from the cache now, you see the replaced insert tag: `2015`

### Side note

In conjunction with #7618 this creates cases where the insert tags are _never_ recursively replaced, and thus always visible with every page load, when the cache is active.

**Comment by leofeyer** [comment] 2015-03-23 12:30
I can reproduce the issue, however I'm not sure if we can and want to fix this. Currently, insert tags are not replaced recursively (in terms of `insert_article` adds `date` when being replaced) and I don't know what impact it had on the performance if we changed it

@contao/developers What do you think?

**Comment by fritzmg** [comment] 2015-03-23 12:36
> Currently, insert tags are not replaced recursively (in terms of insert_article adds date when being replaced)

Hm, that's odd, why does it work if you do not use the page cache or when the page is loaded from the cache? The problem only occurs, if the page is generated for the cache for the first time. It does not occur, if you do not use the page cache at all.

**Comment by leofeyer** [comment] 2015-03-23 13:22
>  why does it work if you do not use the page cache or when the page is loaded from the cache?

No idea about the first one (not using the page cache). The second one is logical, because the insert tag has been cached and is now replaced upon output.

**Comment by leofeyer** [comment] 2015-03-26 19:56
The problem is caused by the internal cache of `Controller::replaceInsertTags()` now being static. See the discussion here: https://github.com/contao/core/issues/4402#issuecomment-7083783

@contao/developers How to solve the problem? Revert `static $arrCache` to `$arrCache`?

**Comment by leofeyer** [comment] 2015-03-26 20:05
My current (and probably correct) fix is to replace every occurrence of `$arrCache[$strKey]` with `$arrCache[$blnCache][$strKey]`, so there is one cache for insert tags being replaced for caching and another one for insert tags being replaced for outputting. However, this means twice the RAM.

**Comment by discordier** [comment] 2015-03-26 22:58
How much RAM do you expect there to be in use?
I suspect it will be around some kb and therefore neglectable.

**Comment by leofeyer** [comment] 2015-03-27 08:06
I think so, too, still I wanted to mention it.

**Comment by leofeyer** [comment] 2015-03-27 08:46
Fixed in 81f450995868a7094351e85417938e8ec10fafd5.

**Closed by leofeyer** 2015-03-27 08:46 UTC
Labels: defect, up for discussion
