### ISSUE TITLE
Camera Slideshow broken in 3.5.11

### ISSUE THREAD

**Issue by Whissi** [contao/core#8319] opened 2016-04-21 13:02 UTC
After upgrading from contao-3.5.9 to v3.5.11 the camera slideshows aren't working anymore:

<img width="808" alt="screen shot 2016-04-21 at 15 00 58" src="https://cloud.githubusercontent.com/assets/729436/14709638/f44c1d18-07d1-11e6-9321-03a12d999563.png">

When I downgrade back to 3.5.9 the slideshows will work again.

**Comment by aschempp** [comment] 2016-04-21 13:06
What is camera slideshows?

**Comment by bytehead** [comment] 2016-04-21 13:06
Maybe related to #8317

**Comment by leofeyer** [comment] 2016-04-21 13:12
Most likely a duplicate of #8317.

**Comment by Whissi** [comment] 2016-04-21 13:12
Sorry, I forgot that this was a 3rd party plugin (https://contao.org/de/erweiterungsliste/view/cameraslideshow.de.html).

**Closed by leofeyer** 2016-04-21 13:12 UTC
