### ISSUE TITLE
 heredity of page layouts to subpages

### ISSUE THREAD

**Issue by codiso** [contao/core#8751] opened 2017-07-27 08:28 UTC
If I have a page with a lot of sub pages and i whant to apply an page layout to this page all subpages also use this layout. This is the normal contao behavior. Sometimes I only want to apply the page layout to this special page and not to all subpages!

To get this done I have to assign all subpages a other page layout too. This is a very annoying work!

Would it be possible to switch the heredity of page layouts on and off manually?

**Comment by ausi** [comment] 2017-07-27 08:44
Related: #3647

**Comment by Aybee** [comment] 2017-07-27 08:47
I get your idea. But in almost all cases you will find a solution without an extra page layout for this pages. If this feature request will not get accepted you can ask for a solution in the forum. Either without an extra page layout or how to disable the inheritance.

Stripping down your layouts to the minimum of one increases the ease of layout maintenance significant.

**Comment by asaage** [comment] 2017-07-27 12:32
Another way to achieve this is to pull these special pages out of the inheritance-tree: put them aside, hide them from menues and create an internal-redirect-page in the original position.
Though this might not look intuitive for a customer i practiced this more than once.

**Comment by codiso** [comment] 2017-07-27 12:40
This is a workarround, but does not work if your pages have modules inside (e.g. navigations) which rely on the original page tree :-(

**Comment by leofeyer** [comment] 2017-08-10 13:54
Duplicate of #3647

**Closed** 2017-08-10 13:54 UTC
Labels: feature, up for discussion
