### ISSUE TITLE
"Publish Article" is defect. Click on it without saving publish the article

### ISSUE THREAD

**Issue by havutcuoglu** [contao/core#8766] opened 2017-08-10 11:11 UTC
Hey core team,

the "publish article" checkbox is defect. Click on "publish article" trigger load the page new and show users the options "show from" and "show until". 

But the problem is, if you click on "publish article" the page is already saved without click on save button and u can see the content in frontend. This is not correct. Then it makes no difference whether I enter in the "show from" or "show until". The options "show from" and "show until" muss be there before i check the "publish article".

Thanks in advance.

**Comment by fritzmg** [comment] 2017-08-10 11:22
This has already been changed in Contao 4.4.2

**Comment by havutcuoglu** [comment] 2017-08-10 11:50
Ok. But I am using the LTS 3.5.x. version. When is it fixed on this?

**Comment by derastronaut** [comment] 2017-08-10 11:55
I can reproduce the issue. (3.5.28)

You don't need to push the save-button.

**Comment by fritzmg** [comment] 2017-08-10 12:29
Duplicate of https://github.com/contao/core/issues/8736 basically.

**Comment by leofeyer** [comment] 2017-08-10 12:33
We need to back port the changes from contao/core-bundle#908.

**Comment by havutcuoglu** [comment] 2017-08-10 12:36
Thanks for everyone.

**Comment by leofeyer** [comment] 2017-08-16 09:26
Back ported in a66ce781f555aadca5d994533a3cf6a251cff20c.

**Closed by leofeyer** 2017-08-16 09:26 UTC
Labels: defect
