### ISSUE TITLE
Bug: Versions::restore() tries to set data for primary keys and Indizes in statement

### ISSUE THREAD

**Issue by fatcrobat** [contao/core#7905] opened 2015-06-30 13:22 UTC
Tried to restore an previously created version of an news within an fresh contao installation, resulting in the following error.

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY='', pid_start_stop_published='' WHERE id='1'' at line 1 (UPDATE tl_news SET id='1', pid='2', tstamp='1435669478', headline='123123c', alias='123c12', author='1', date='1435669440', time='1435669440', subheadline='', teaser='
312c3123c123c

', addImage='', singleSRC=NULL, alt='', size='', imagemargin='', imageUrl='', fullsize='', caption='', floating='above', addEnclosure='', enclosure=NULL, source='default', jumpTo='0', articleId='0', url='', target='', cssClass='', noComments='', featured='', published='1', start='', stop='', PRIMARY='', pid_start_stop_published='' WHERE id='1') thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/classes/Versions.php(269): Contao\Database\Statement->execute('1')
#2 system/modules/core/drivers/DC_Table.php(1769): Contao\Versions->restore('1')
#3 system/modules/core/classes/Backend.php(639): Contao\DC_Table->edit()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```

MySQL Server Version: 5.5.43
PHP-Version:  5.5.9

What i figured out so far, is that in line 257  every field from the table is stored in $data, and in the foreach loop in line 262 the Table Indizes and Keys were not removed from $data properly.

```
// Get the currently available fields
$arrFields = array_flip($this->Database->getFieldnames($this->strTable));

// Unset fields that do not exist (see #5219)
$data = array_intersect_key($data, $arrFields);

$this->loadDataContainer($this->strTable);

// Reset fields added after storing the version to their default value (see #7755)
foreach (array_diff_key($arrFields, $data) as $k=>$v)
{
$data[$k] = \Widget::getEmptyValueByFieldType($GLOBALS['TL_DCA'][$this->strTable]['fields'][$k]['sql']);
}
```

**Comment by aschempp** [comment] 2015-06-30 13:28
Duplicate of https://github.com/contao/core/issues/7869

**Closed** 2015-06-30 13:28 UTC
Labels: duplicate
