### ISSUE TITLE
Updater::updateFileTreeFields might fail with fatal error if module was disabled

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8304] opened 2016-04-12 08:56 UTC
If a module is disabled via `.skip` file and its database tables and fields were dropped before updating the Contao installation, [`Updater::updateFileTreeFields`](https://github.com/contao/core/blob/3.5.9/system/modules/core/library/Contao/Database/Updater.php#L685) will fail with a fatal error, e.g.

```
Fatal error: Uncaught exception Exception with message Query error: Table '….tl_faq' doesn't exist (SHOW FULL COLUMNS FROM tl_faq) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
```

(in this case the `faq` module was disabled), since there are no checks whether the tables (and fields) belonging to the DCAs actually exist.

**Comment by leofeyer** [comment] 2016-06-13 15:08
So what is the solution here? @contao/developers Should we ignore modules with `.skip` files?

**Comment by aschempp** [comment] 2016-06-13 15:08
I can't see a reason why not?

**Comment by fritzmg** [comment] 2016-06-13 15:15
A module might be (temporarily) disabled with intact database data. Thus if you skip it during the update process, it might lead to problems afterwards, would it not?

**Comment by leofeyer** [comment] 2016-06-13 15:24
Of course. But you are not supposed to disable a module which you plan to use later. And you are neither supposed to drop database fields of a module that is only temporarily disabled.

**Comment by fritzmg** [comment] 2016-06-13 15:27
Yeah, I suppose ignoring modules with `.skip` files is good enough then.

**Comment by leofeyer** [comment] 2016-06-14 11:56
Well, it is not. See #6058 for the details.

As I said above, this is an edge case resulting from something your should not do (and probably would not do) in reality. We should not fix it at all IMHO.

**Comment by fritzmg** [comment] 2016-06-15 13:38
? Disabling modules is something that you should not do? Or what exactly do you mean?

**Comment by leofeyer** [comment] 2016-06-15 13:51
No, you should not remove database fields if you know that a module is only temporarily disabled.

**Comment by fritzmg** [comment] 2016-06-15 14:19
Yes, but that was not the use case where this problem occurred for me and another user on the forum. We have disabled modules without any intention of re enabling them later, or at least for the time being.

**Comment by fritzmg** [comment] 2016-06-15 18:52
Just to describe the use case and reproduction again:

* a long time ago, we made a website with Contao `3.1.5`.
* Since the website did not use some of the core modules, nor were there any plans to use them ever in the future, e.g. the `events`, `faq` and `newsletter` modules in this case, they were disabled and their database tables were dropped (otherwise they would show up on every database update).
* Recently, this Contao installation was updated to Contao `3.5.12`. When running the database updates via the Install Tool after updating the files to the newest version, the problem described in the first post occurs.

Just to reiterate: this happens because in this case the `events` and `faq` module was disabled and will stay disabled forever. _They were_ __not__ _temporarily disabled_.

See also https://community.contao.org/de/showthread.php?62062-Update-von-3-0-6-auf-3-5-9-Aufruf-Installtool-Fehlermeldung&p=405233&viewfull=1#post405233

**Comment by Aybee** [comment] 2016-06-16 16:06
I think this old ticket belongs to this topic https://github.com/contao/core/issues/4622

The problem is that contao animates us to delete tables of inactive extensions on DB update.

**Comment by fritzmg** [comment] 2016-06-16 16:40
I don't see that as a problem though. If I disable an extension, I might as well want to remove its database tables.

**Comment by discordier** [comment] 2016-06-18 01:04
The database update must check if tables/fields it wants to modify do exist before tampering with them.
Disabling core extensions is a very valid use case.

**Comment by leofeyer** [comment] 2016-07-21 14:20
@fritzmg Can you please post the stack trace of the error? We cannot find the place in the code where the problem occurs.

**Comment by fritzmg** [comment] 2016-07-21 14:25
It should happen here https://github.com/contao/core/blob/3.5.15/system/modules/core/library/Contao/Database/Updater.php#L745 for example (since there is no check whether the table actually exists), but I'll make a full reproduction if necessary and post the stack trace when I have the time.

To reproduce it, you have to

1. Install Contao `>=3.0,<3.2`
2. Disable e.g. the `faq` module and drop its tables
3. Update to Contao `>=3.2` and run the database upgrades in the Install Tool

**Comment by leofeyer** [comment] 2016-07-21 15:17
We need the full stack trace please.

**Comment by fritzmg** [comment] 2016-07-22 15:57
Ah, Hagen already posted the full stack trace in the forum post I linked:
```
Fatal error: Uncaught exception Exception with message Query error: Table 'db393966_3.tl_faq' doesn't exist (SHOW FULL COLUMNS FROM tl_faq) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('SHOW FULL COLUM...')
#1 system/modules/core/library/Contao/Database/Mysql.php(131): Contao\Database->query('SHOW FULL COLUM...')
#2 system/modules/core/library/Contao/Database.php(300): Contao\Database\Mysql->list_fields('tl_faq')
#3 system/modules/core/library/Contao/Database.php(322): Contao\Database->listFields('tl_faq', true)
#4 system/modules/core/library/Contao/Database/Updater.php(745): Contao\Database->fieldExists('singleSRC', 'tl_faq', true)
#5 system/modules/core/library/Contao/Database/Updater.php(545): Contao\Database\Updater->updateFileTreeFields()
#6 system/modules/core/controllers/BackendInstall.php(1130): Contao\Database\Updater->run32Update()
#7 system/modules/core/controllers/BackendInstall.php(516): Contao\BackendInstall->update32()
#8 system/modules/core/controllers/BackendInstall.php(171): Contao\BackendInstall->runDatabaseUpdates()
#9 contao/install.php(24): Contao\BackendInstall->run()
#10 {main}
```

**Comment by fritzmg** [comment] 2016-07-22 16:15
This seems to happen only under specific circumstances. Usually `updateFileTreeFields` will not make it past [here](https://github.com/contao/core/blob/3.5.9/system/modules/core/library/Contao/Database/Updater.php#L738):
```php
if (is_array($GLOBALS['TL_DCA'][$strTable]['fields']))
```
because when the DCA is loaded, only the active modules get loaded: https://github.com/contao/core/blob/3.5.9/system/modules/core/library/Contao/DcaLoader.php#L80
```php
foreach (\ModuleLoader::getActive() as $strModule)
```
__unless__ the DCA happens to be in the cache:
```php
if (!\Config::get('bypassCache') && file_exists(TL_ROOT . '/' . $strCacheFile))
{
	include TL_ROOT . '/' . $strCacheFile;
}
```
Not sure if this is the reason why it happened for me and Hagen. Would be pretty unusual.

**Comment by aschempp** [comment] 2016-07-22 16:37
Sounds like a good idea to clear the internal cache on migration anyway?

**Comment by fritzmg** [comment] 2016-07-26 12:23
Indeed. I cannot reproduce this issue in any other way currently, so may be this ticket can be closed.

**Comment by discordier** [comment] 2016-07-27 01:41
I would leave it open to have a reminder to clear the cache.

**Comment by leofeyer** [comment] 2016-11-16 12:09
So the solution is to clear the internal cache before executing `BackendInstall::runDatabaseUpdates()`?

**Comment by aschempp** [comment] 2016-11-17 09:19
I cannot see a reason not to do that. Performance is not relevant for the DB updates, but having the latest information sure is.

**Comment by leofeyer** [comment] 2016-11-17 09:42
I rather meant "does clearing the internal cache really fix the issue"?

**Comment by aschempp** [comment] 2016-11-17 11:22
Actually what @discordier [wrote months ago](https://github.com/contao/core/issues/8304#issuecomment-226912737) certainly is the right solution. We should

 1. Ignore/drop the cache
 2. make sure any table and/or field exists before tampering it

shouldn't be hard to do…

**Comment by leofeyer** [comment] 2016-11-23 15:51
Fixed in f959396e1ba10e0e278c7d3ce6d990bd1ce622c4.

**Closed by leofeyer** 2016-11-23 15:51 UTC
Labels: defect

**Comment by aschempp** [comment] 2016-11-23 16:30
You should also check if the field exists!

**Comment by leofeyer** [comment] 2016-11-23 16:35
No, that is not a problem. If you disable a module, its tables will be removed. There is no way to keep the table and remove a single field only, therefore this case can never occur. (Unless you manually modify the database structure.)

**Comment by ausi** [comment] 2016-11-23 16:38
> If you disable a module, its tables will be removed.

But a module can also extend core tables like `tl_module`, not only create its own.

**Comment by aschempp** [comment] 2016-11-23 16:39
>  (Unless you manually modify the database structure.)

Or if you did not update the tables after updating something.

**Comment by leofeyer** [comment] 2016-11-23 16:51
> But a module can also extend core tables like `tl_module`

Yes, but those tables always exist, don't they?

Let's do it this way: If you can set up a real use case, which I can reproduce, I'll add the field check.

**Comment by aschempp** [comment] 2016-11-23 16:53
Pretty simple: Update a Contao extension prior to the migration and don't upgrade the DB fields.

**Comment by leofeyer** [comment] 2016-11-23 16:55
No idea what you mean. Is this even possible with the ER2?

**Comment by aschempp** [comment] 2016-11-23 16:56
Absolutely. You can install the latest `changelanguage` in Contao 2.11 even if it's not supported.

**Comment by ausi** [comment] 2016-11-23 20:42
> You should also check if the field exists!

I think the existence of the field is already checked in https://github.com/contao/core/commit/f959396e1ba10e0e278c7d3ce6d990bd1ce622c4#diff-384cc83f838e2de4e1d4aff608272173R751
