### ISSUE TITLE
Controller::generateFrontendUrl() should respect the language of the page's root page

### ISSUE THREAD

**Issue by ben-eSM** [contao/core#6743] opened 2014-02-18 09:35 UTC
Currently the ```Controller::generateFrontendUrl()``` isn't respecting the page's language, set by it's RootPage. That can results in not-working links like if you have a Multi-Language setup and you decide against language specific events.
Let's say you have the eventreader on the German page. If you include the eventlist with the German events in the English page, the links to the reader page will result in a 404, because the language flag of the current RootPage (en) will be used instead of the one of the reader page.

Since this behavior isn't intended, this should be considered a bug in my opinion. Therefore it should be fixed for Contao 3.2 also.

**Comment by fritzmg** [comment] 2015-07-22 12:54
As it stands currently: setting an __internal redirect__ in a news entry to a page of a different page root with either a different language or domain (which is perfectly possible in Contao) will result in an erroneous URL. Surely this cannot be intended behaviour. Some people might misuse this as a "feature", but that's just working around a completely different issue by using this misbehaviour.

If it is indeed intended behaviour, then the page tree picker would need to disallow the selection of pages in website roots that use a different language or domain than the news archive's jumpTo page.

**Comment by fritzmg** [comment] 2015-12-08 12:02
In the mean time I have also fixed the erroneous behaviour of the news archive's target page in my extension for Contao 3:

* [[news_domainfix](https://contao.org/en/extension-list/view/news_domainfix.en.html)]
* [fritzmg/contao-news-domainfix](https://github.com/fritzmg/contao-news-domainfix)

Both for target pages on a different language or domain.

**Comment by fritzmg** [comment] 2016-05-18 18:47
Isn't this actually fixed now since Contao `3.5.7` or at least `3.5.12`?

**Comment by leofeyer** [comment] 2016-06-03 17:09
Yes it is.

**Closed by leofeyer** 2016-06-03 17:09 UTC
