### ISSUE TITLE
"The registry already contains an instance" error in Backend::addFileMetaInformationToRequest

### ISSUE THREAD

**Issue by paha77** [contao/core#8443] opened 2016-08-19 08:02 UTC
If we save a content element with the type "text" and there's a function call, for example in a save_callback function which loads the parent page with 

```php
$objPage = \PageModel::findById($page_id);
```

the tl_content::storeFileMetaInformation function (defined in the tl_content dca as save_callback) fails, because it calls the Backend::addFileMetaInformationToRequest function and in this function the following code is executed:

```php
if ($objPage === null || $objPage->numRows < 1)
{
	return;
}

$objModel = new \PageModel();
$objModel->setRow($objPage->row());
$objModel->loadDetails();
```

If I use these calls instead, the problem is solved:

```php
if ($objPage === null || $objPage->numRows < 1 || !$objPage->id)
{
	return;
}

$objModel = \PageModel::findById($objPage->id);
$objModel->loadDetails();
```

**Comment by leofeyer** [comment] 2016-08-19 09:24
This should have been fixed in #6467 already. Which Contao version are you using?

**Comment by fritzmg** [comment] 2016-08-19 09:34
In #6467 the error happens within the old `CalendarEventsModell::findBoundaries` function, which was removed then. Here it happens in `Backend::addFileMetaInformationToRequest` apparently.

I cannot reproduce the issue though. I tried with
```php
$GLOBALS['TL_DCA']['tl_content']['fields']['text']['save_callback'][] = function($varValue, \DataContainer $dc)
{
	$objPage = \PageModel::findById( \ArticleModel::findById( $dc->activeRecord->pid )->pid );
	return $varValue;
};
```
and saved a text element (which has an image selected).

**Comment by paha77** [comment] 2016-08-19 09:36
Sorry, I'm using 3.5.15.

@fritzmg could you try calling 

```php
$objPage->loadDetails();
```

**Comment by fritzmg** [comment] 2016-08-19 09:40
Still no error.

**Comment by fritzmg** [comment] 2016-08-19 09:48
Yes, I can confirm the problem.

## Reproduction:

* insert the following code in your `dcaconfig.php`:
````php
$GLOBALS['TL_DCA']['tl_content']['fields']['text']['save_callback'][] = function($varValue, \DataContainer $dc)
{
    $objPage = \PageModel::findById(\ArticleModel::findById($dc->activeRecord->pid)->pid);
    return $varValue;
};
```
* go to the file manager, choose a test image and fill it with meta information (just a title for example)
* create a new content element of type `text`, fill in some values for the `text` field and choose the test image with meta information
* save

The image field will show the following error below:
```
The registry already contains an instance for tl_page::id(535)
```

**Comment by leofeyer** [comment] 2016-08-19 09:50
Yes, sorry, I have linked the wrong ticket. The issue should have been fixed in #8224.

**Comment by paha77** [comment] 2016-08-19 09:50
Thank you @fritzmg. So the point is that the image has some metadata.  Is my proposal right?  Does it solve the problem?

**Comment by fritzmg** [comment] 2016-08-19 09:53
Your fix looks good to me. I am wondering why the Page Model isn't loaded this way in the first place.

**Comment by paha77** [comment] 2016-08-19 10:00
Yes it's unnecessary to fetch the data from tl_page twice.  Could it be a problem with the setRow() function?

**Comment by leofeyer** [comment] 2016-08-19 10:04
I can also reproduce the issue but I have no idea why it occurs. We are currently keeping a clone of the original model in the registry if `preventSaving()` is called; if I change this, the error goes away.

@contao/developers /cc

**Comment by fritzmg** [comment] 2016-08-19 10:14
The problem is, that `preventSaving` calls `detach`, and `detach` calls `$this->cloneOriginal()->attach()` which clones the `PageModel` object of `Backend::addFileMetaInformationToRequest` and `attach` adds it to the registry - but the page already is in the registry due to `\PageModel::findById(…)` in the `save_callback`.

**Comment by paha77** [comment] 2016-08-19 10:34
@fritzmg: this is what I've made in my proposal but it must be somehow merged together with the query finding the page ID itself.

**Comment by fritzmg** [comment] 2016-08-19 10:41
The query does not only find the ID, it loads the complete page information from the database and then creates a Model with it.

Maybe the following code can be used instead:
```php
$objModel = \Model\Registry::fetch('tl_page', $objPage->id);

if ($objModel === null)
{
	$objModel->setRow($objPage->row());
	$objModel->loadDetails();
}
```

**Comment by leofeyer** [comment] 2016-08-25 09:37
I have further debugged the issue.

```
string(8) "register"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45300000000333e0d9a" // 2ea453

string(12) "load details"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45e00000000333e0d9a" // 2ea45e (!)

string(14) "prevent saving"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45e00000000333e0d9a" // 2ea45e

string(6) "detach"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45e00000000333e0d9a" // 2ea45e

string(12) "attach clone"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45d00000000333e0d9a" // 2ea45d (!)

string(8) "register"
string(16) "Contao\PageModel"
string(1) "2"
string(32) "00000000002ea45d00000000333e0d9a" // 2ea45d
```

So basically, the first registered page model with ID 2 is not the same as the one we are calling `loadDetails()` on, therefore `detach()` does not unregister the initial page model and when it tries to register the clone, the exception occurs.

@contao/developers Any idea why this is? And why do we attach a clone at all?

**Comment by leofeyer** [comment] 2016-08-25 09:41
Here's my proposed fix:

```php
public function detach($blnKeepClone=true)
{
	\Model\Registry::getInstance()->unregister($this);

	if (!$blnKeepClone)
	{
		return;
	}

	try
	{
		$this->cloneOriginal()->attach();
	}
	catch (\RuntimeException $e)
	{
		// another model is already registered (see #8443)
	}
}
```

**Comment by leofeyer** [comment] 2016-08-26 09:36
The correct fix is in #8450.

**Closed by leofeyer** 2016-08-26 09:36 UTC
Labels: defect

**Comment by sleitz** [comment] 2017-08-02 09:59
This issue unexpectedly resurfaced in one of our Contao 4.4.2 installations. Same message as original post. Is this a regression? We will investigate a bit and might open a new ticket. Or rather here?

**Comment by aschempp** [comment] 2017-08-02 10:00
Better create a new issue I think
